name: Code Style

on: [push, pull_request]

jobs:
  lint:
    name: "Lint Code Base"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install fastFMM
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: fastFMM
          dependencies: true

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.x"
          python-version: 3.9

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Check with black
        run: |
          uv run black . --check --diff

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run flake8 . --count --max-line-length=88 --statistics --exclude .venv   

      - name: Run GitHub super-linter
        uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_HTML: true
          VALIDATE_R: true
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_DOCKER: true
          VALIDATE_ENV: true
